### ISSUE TITLE
[kube-prometheus-stack/grafana] grafana-sc-datasources Init CrashLoopBackOff Caused by SSLError

### ISSUE THREAD

**Issue by bluefishforsale** [prometheus-community/helm-charts#1532]
### Describe the bug a clear and concise description of what the bug is.

Installing v20.0.1 of kubernetes-prometheus-stack leaves grafana in a non-running state.
This appears to be due to the init container `grafana-sc-datasources` which has been mentioned in [github.com/helm/charts/issues/20699](https://github.com/helm/charts/issues/20699)

My issue also points at SSL TLS verification failing. I have tried disabling the TLS also to no effect.

### What's your helm version?

v3.6.3

### What's your kubectl version?

Major:"1", Minor:"20", GitVersion:"v1.20.2

### Which chart?

grafana

### What's the chart version?

20.0.1  /  0.52.0

### What happened?

```
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
prom                    default         1               2021-11-23 17:11:59.929094 -0800 PST    deployed        kube-prometheus-stack-20.0.1    0.52.0 

default          prom-kube-prometheus-stack-operator-797d6f6679-mdbh2           ●         1/1                        0 Running                                0          0           n/a           n/a           n/a           n/a 10.244.1.56           node005         3m18s          
default          prom-kube-state-metrics-759457c944-dpcq6                       ●         1/1                        0 Running                                0          0           n/a           n/a           n/a           n/a 10.244.1.57           node005         3m18s          
default          prom-grafana-67b7849f48-zzmnn                                  ●         0/2                        0 Init:CrashLoopBackOff                  0          0           n/a           n/a           n/a           n/a 10.244.1.58           node005         3m17s          
default          prom-prometheus-node-exporter-c4254                            ●         1/1                        0 Running                                0          0           n/a           n/a           n/a           n/a 192.168.1.104         node004         3m17s          
default          prom-prometheus-node-exporter-lc5zf                            ●         1/1                        0 Running                                0          0           n/a           n/a           n/a           n/a 192.168.1.102         node002         3m17s          
default          prom-prometheus-node-exporter-lgvv6                            ●         1/1                        0 Running                                0          0           n/a           n/a           n/a           n/a 192.168.1.106         node006         3m17s          
default          prom-prometheus-node-exporter-ttfjl                            ●         1/1                        0 Running                                0          0           n/a           n/a           n/a           n/a 192.168.1.103         node003         3m17s          
default          prom-prometheus-node-exporter-txjgq                            ●         1/1                        0 Running                                0          0           n/a           n/a           n/a           n/a 192.168.1.105         node005         3m17s          
default          prom-prometheus-node-exporter-wxl4x                            ●         1/1                        0 Running                                0          0           n/a           n/a           n/a           n/a 192.168.1.101         node001         3m17s         
default          alertmanager-prom-kube-prometheus-stack-alertmanager-0         ●         2/2                        0 Running                                0          0             0           n/a             0           n/a 10.244.3.131          node006         3m14s          
default          prometheus-prom-kube-prometheus-stack-prometheus-0             ●         2/2                        0 Running                                0          0             0           n/a             0           n/a 10.244.3.132          node006         3m14s          

# LOGS FROM THE FAILING POD
 grafana-sc-datasources [2021-11-24 01:17:57] Starting collector
 grafana-sc-datasources [2021-11-24 01:17:57] No folder annotation was provided, defaulting to k8s-sidecar-target-directory                                                                                         grafana-sc-datasources [2021-11-24 01:17:57] Selected resource type: ('secret', 'configmap')
 grafana-sc-datasources [2021-11-24 01:17:57] Loading incluster config ...                                                                                                                                          grafana-sc-datasources [2021-11-24 01:17:57] Config for cluster api at 'https://10.32.0.1:443' loaded...
 grafana-sc-datasources [2021-11-24 01:17:57] Unique filenames will not be enforced.                                                                                                                                grafana-sc-datasources [2021-11-24 01:17:57] 5xx response content will not be enabled.
 grafana-sc-datasources Traceback (most recent call last):                                                                                                                                                          grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
 grafana-sc-datasources     httplib_response = self._make_request(                                                                                                                                                  grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
 grafana-sc-datasources     self._validate_conn(conn)                                                                                                                                                               grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
 grafana-sc-datasources     conn.connect()                                                                                                                                                                          grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
 grafana-sc-datasources     self.sock = ssl_wrap_socket(                                                                                                                                                            grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 453, in ssl_wrap_socket
 grafana-sc-datasources     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)                                                                                                                             grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl
 grafana-sc-datasources     return ssl_context.wrap_socket(sock)                                                                                                                                                    grafana-sc-datasources   File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
 grafana-sc-datasources     return self.sslsocket_class._create(                                                                                                                                                    grafana-sc-datasources   File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
 grafana-sc-datasources     self.do_handshake()                                                                                                                                                                     grafana-sc-datasources   File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
 grafana-sc-datasources     self._sslobj.do_handshake()
 grafana-sc-datasources ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)
 grafana-sc-datasources During handling of the above exception, another exception occurred:
 grafana-sc-datasources Traceback (most recent call last):
 grafana-sc-datasources   File "/app/sidecar.py", line 124, in <module>
 grafana-sc-datasources     main()
 grafana-sc-datasources   File "/app/sidecar.py", line 84, in main
 grafana-sc-datasources     list_resources(label, label_value, target_folder, request_url, request_method, request_payload,
 grafana-sc-datasources   File "/app/resources.py", line 80, in list_resources
 grafana-sc-datasources     ret = getattr(v1, _list_namespace[namespace][resource])(**additional_args)
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 15938, in list_namespaced_secret
 grafana-sc-datasources     return self.list_namespaced_secret_with_http_info(namespace, **kwargs)  # noqa: E501
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 16049, in list_namespaced_secret_with_http_info
 grafana-sc-datasources     return self.api_client.call_api(
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
 grafana-sc-datasources     return self.__call_api(resource_path, method,
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
 grafana-sc-datasources     response_data = self.request(
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
 grafana-sc-datasources     return self.rest_client.GET(url,
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 239, in GET
 grafana-sc-datasources     return self.request("GET", url,
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 212, in request
 grafana-sc-datasources     r = self.pool_manager.request(method, url,
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 74, in request
 grafana-sc-datasources     return self.request_encode_url(
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 96, in request_encode_url
 grafana-sc-datasources     return self.urlopen(method, url, **extra_kw)
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
 grafana-sc-datasources     response = conn.urlopen(method, u.request_uri, **kw)
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
 grafana-sc-datasources     return self.urlopen(
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
 grafana-sc-datasources     return self.urlopen(
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
 grafana-sc-datasources     return self.urlopen(
 grafana-sc-datasources   [Previous line repeated 2 more times]
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
 grafana-sc-datasources     retries = retries.increment(
 grafana-sc-datasources   File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
 grafana-sc-datasources     raise MaxRetryError(_pool, url, error or ResponseError(cause))
 grafana-sc-datasources urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.32.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/default/secrets?labelSelector=grafana_datasource (Cau
 sed by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))
 grafana-sc-datasources stream closed
```

### What you expected to happen?

Grafana Pod to be started as requested

## Add repo
$ helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
$ helm repo update
See helm repo for command documentation.

## Install Chart
$ helm install prom prometheus-community/kube-prometheus-stack

### Enter the changed values of values.yaml?

Null

### Enter the command that you execute and failing/misfunctioning.

helm install prom prometheus-community/kube-prometheus-stack

### Anything else we need to know?

I am using Flannel for my CNI
Pods  10.244.0.0/16
Services 10.32.0.0/16
nodes are 192.168.1.0/24

My kubernetes service api is 10.32.0.1
kubernetes.default.svc.cluster.local

My Kubernetes SSL certs are self-genrated
This is a hand-built cluster. I currently run many pods / services / ingress / pv / pvcs.
The sole problem in my cluster talking to this root API is grafana TLS verification. 
Therefore I think the issue lies there.

**Comment by bluefishforsale** [comment]
Update: 

I feel like an idiot. I went and read the grafana heml chart and found the value being used to ignore TLS
```
      {{- if .Values.sidecar.skipTlsVerify }}
      - name: SKIP_TLS_VERIFY
        value: "{{ .Values.sidecar.skipTlsVerify }}"
      {{- end }}
 ```
 
 so I set that in the values.yaml for kube-prometheus-stacl
 ```
grafana:
   sidecar:
    skipTlsVerify: true
```

as you might have guessed, it works now.
