### ISSUE TITLE
[kube-prometheus-stack] Datasources reloading failed over HTTPS

### ISSUE THREAD

**Issue by d7volker** [prometheus-community/helm-charts#1779]
### Describe the bug a clear and concise description of what the bug is.

I got the following error message, an Grafana ended up with no datasource.

`[2022-02-08 09:53:09] Starting collector
[2022-02-08 09:53:09] No folder annotation was provided, defaulting to k8s-sidecar-target-directory
[2022-02-08 09:53:09] Selected resource type: ('secret', 'configmap')
[2022-02-08 09:53:09] Loading incluster config ...
[2022-02-08 09:53:09] Config for cluster api at 'https://198.18.128.1:443' loaded...
[2022-02-08 09:53:09] Unique filenames will not be enforced.
[2022-02-08 09:53:09] 5xx response content will not be enabled.
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host '198.18.128.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host '198.18.128.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
[2022-02-08 09:53:14] Working on ADDED configmap grafana/prometheus-kube-prometheus-grafana-datasource
[2022-02-08 09:53:47] Received unknown exception: HTTPSConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/admin/provisioning/datasources/reload (Caused by SSLError(CertificateError("hostname 'localhost' doesn't match either of '*.example.com'")))

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 469, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 542, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_match_hostname.py", line 152, in match_hostname
    raise CertificateError(
urllib3.util.ssl_match_hostname.CertificateError: hostname 'localhost' doesn't match either of '*.example.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/admin/provisioning/datasources/reload (Caused by SSLError(CertificateError("hostname 'localhost' doesn't match either of '*.example.com'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/resources.py", line 239, in _watch_resource_loop
    _watch_resource_iterator(*args)
  File "/app/resources.py", line 227, in _watch_resource_iterator
    request(request_url, request_method, enable_5xx, request_payload)
  File "/app/helpers.py", line 123, in request
    res = r.post("%s" % url, auth=auth, json=payload, timeout=REQ_TIMEOUT)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)`

I ensured the setting is set: 

skipTlsVerify: true

And I verified it in the sidecar container:

/app $ env |grep SKIP
SKIP_TLS_VERIFY=true

### What's your helm version?

v3.8.0

### What's your kubectl version?

v1.23.3

### Which chart?

kube-prometheus-stack

### What's the chart version?

30.2.0

### What happened?

I got this exception on the initial load and the reload of datasources:

`[2022-02-08` 09:53:14] Working on ADDED configmap grafana/prometheus-kube-prometheus-grafana-datasource
[2022-02-08 09:53:47] Received unknown exception: HTTPSConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/admin/provisioning/datasources/reload (Caused by SSLError(CertificateError("hostname 'localhost' doesn't match either of '*.example.com'")))

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 469, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 542, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_match_hostname.py", line 152, in match_hostname
    raise CertificateError(
urllib3.util.ssl_match_hostname.CertificateError: hostname 'localhost' doesn't match either of '*.example.com'`

### What you expected to happen?

It is working no matter of the TLS certificate.

### How to reproduce it?

- Configure Garafana to accept HTTPS connections.
- Setting skipTlsVerify: true in the sidecar configuration
- And pointing the reloadURL to:

reloadURL: "https://localhost:3000/api/admin/provisioning/datasources/reload" 

### Enter the changed values of values.yaml?

below sidecar:

`skipTlsVerify: true
reloadURL: "https://localhost:3000/api/admin/provisioning/datasources/reload" 

grafana.ini:
  paths:
  data: /var/lib/grafana/
  logs: /var/log/grafana
  plugins: /var/lib/grafana/plugins
  provisioning: /etc/grafana/provisioning
  analytics:
  check_for_updates: true
  log:
     mode: console
  grafana_net:
     url: https://grafana.net
  server:
     protocol: https
     cert_file: /etc/grafana/tls/tls.crt
     cert_key: /etc/grafana/tls/tls.key`

### Enter the command that you execute and failing/misfunctioning.

helm install -f myvalues.yaml prometheus ./kube-prometheus-stack

**Comment by d7volker** [comment]
I have seen, this is probably not for you, because I am refering to the Grafana Helm chart.
