### ISSUE TITLE
[prometheus-smartctl-exporter] /usr/sbin/smartctl: no such file or directory

### ISSUE THREAD

**Issue by djjudas21** [prometheus-community/helm-charts#2521]
### Describe the bug a clear and concise description of what the bug is.

I installed prometheus-smartctl-exporter with default values. Pods crash on starting with the following error:

```
[Warning] S.M.A.R.T. output reading error: fork/exec /usr/sbin/smartctl: no such file or directory
panic: runtime error: index out of range [0] with length 0

goroutine 12 [running]:
main.(*SMARTctlInfo).mineVersion(0xc000053e98)
	/app/smartctlinfo.go:59 +0xb99
main.(*SMARTctlInfo).Collect(...)
	/app/smartctlinfo.go:48
main.SMARTctlManagerCollector.Collect({}, 0x0?)
	/app/main.go:51 +0x90
github.com/prometheus/client_golang/prometheus.DescribeByCollect.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/collector.go:90 +0x2b
created by github.com/prometheus/client_golang/prometheus.DescribeByCollect
	/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/collector.go:89 +0x9c
```

`smartctl` is available on all my kube nodes at `/usr/sbin/smartctl`. Does this pod need to mount this binary into the container? There is nothing in the template which mounts `/usr/sbin/smartctl` into the image. 

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-smartctl-exporter/templates/daemonset.yaml#L58

### What's your helm version?

version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}

### What's your kubectl version?

Server Version: v1.22.15-3+6a8fc82baa4d77

### Which chart?

prometheus-smartctl-exporter

### What's the chart version?

0.1.1

### What you expected to happen?

Pod would run and export smartctl metrics on its service

### How to reproduce it?

Install chart with default values

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

```
helm upgrade -i --create-namespace \
    -n monitoring prometheus-smartctl-exporter \
    prometheus-community/prometheus-smartctl-exporter
```

### Anything else we need to know?

I see there is a 0.8.0 tag on the [upstream GitHub repo](https://github.com/prometheus-community/smartctl_exporter/releases) which is not yet available on [Docker Hub](https://hub.docker.com/r/prometheuscommunity/smartctl-exporter/tags). The changelog for v0.8.0 says it has `smartctl` baked into the image.

**Comment by djjudas21** [comment]
I've requested a v0.8.0 image build in https://github.com/prometheus-community/smartctl_exporter/issues/78
