### ISSUE TITLE
prometheus-kube-stack grafana: Readiness probe failed: connect: connection refused

### ISSUE THREAD

**Issue by AndreasMurk** [prometheus-community/helm-charts#4251]
### Describe the bug a clear and concise description of what the bug is.

Hi!

I have deployed the `kube-prometheus-stack` using FluxCD with the latest 56.6.2 version.

Prometheus along with Loki works fine. However, Grafana has some problems after a while.

It lasted approximately 60 minutes to start up fully until all migrations have been done. Then, whenever I make changes in the Dashboard (eg. adding a new data source) the pod fails.
After inspecting the logs I have found these error messages:

```text
{"time": "2024-02-14T15:50:37.062173+00:00", "taskName": null, "msg": "Writing /tmp/dashboards/apiserver.json (ascii)", "level": "INFO"}
{"time": "2024-02-14T15:50:37.065761+00:00", "taskName": null, "msg": "Retrying (Retry(total=4, connect=9, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffaff8f8f80>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/admin/provisioning/dashboards/reload", "level": "WARNING"}
{"time": "2024-02-14T15:50:39.266982+00:00", "taskName": null, "msg": "Retrying (Retry(total=3, connect=8, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffaff8f90a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/admin/provisioning/dashboards/reload", "level": "WARNING"}
{"time": "2024-02-14T15:50:43.669076+00:00", "taskName": null, "msg": "Retrying (Retry(total=2, connect=7, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffaff8f9340>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/admin/provisioning/dashboards/reload", "level": "WARNING"}
{"time": "2024-02-14T15:50:52.471752+00:00", "taskName": null, "msg": "Retrying (Retry(total=1, connect=6, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffaff8f96a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/admin/provisioning/dashboards/reload", "level": "WARNING"}
{"time": "2024-02-14T15:51:10.074029+00:00", "taskName": null, "msg": "Retrying (Retry(total=0, connect=5, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffaff8f9820>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/admin/provisioning/dashboards/reload", "level": "WARNING"}
{"time": "2024-02-14T15:51:10.076283+00:00", "taskName": null, "msg": "Received unknown exception: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/admin/provisioning/dashboards/reload (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffaff8f9a90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "level": "ERROR"}
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

The pod tries to restart but fails with the aformentioned bug. In Lens it always says: `Readiness probe failed: Get "http://192.168.1.247:3000/api/health": dial tcp 192.168.1.247:3000: connect: connection refused`

### What's your helm version?

3.14.0

### What's your kubectl version?

1.29.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

56.6.2

### What happened?

Making changes in the Dashboard (eg. adding new data sources such as Loki) fails with the stated Python error.

What I have also encountered is that since the newest release, the Dashboard seems slower than with previous releases.

### What you expected to happen?

Dashboard should correctly set the datasource

### How to reproduce it?

1. Enable Grafana and Loki in `values.yaml`
2. Deploy using FluxCD or helm
3. Add new Loki Datasource
4. Check if Dashboard / Pod is still running
5. Additionally check logs

### Enter the changed values of values.yaml?

prometheus:
  ingress:
    enabled: true
    annotations: 
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    kubernetes.io/ingressClassName: nginx
    nginx.ingress.kubernetes.io/service-upstream: "true"

      # nginx-http-auth config:
    nginx.ingress.kubernetes.io/auth-type: basic
      # the name of the secret that contains the htpasswd hash (has to exist beforehand)
    nginx.ingress.kubernetes.io/auth-secret: prometheus-htpasswd
      # message to display on auth missing:
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Prometheus'

    hosts:
      - prometheus.xxx

    path: /
    service:
      name: prometheus-prometheus-kube-prometheus-prometheus
      port: 9090
      tls:
        - secretName: prometheus-prod-secret
          hosts:
            - prometheus.xxx
      prometheusSpec:
        replicas: 1
        retention: 168h

        walCompression: true
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "myBlock"
              resources:
                requests:
                  storage: 50Gi

                    # scrape all service monitorings without correct labeling
                  podMonitorSelectorNilUsesHelmValues: false
                  serviceMonitorSelectorNilUsesHelmValues: false
                  grafana:
                    admin:
                      existingSecret: grafana-admin-secret
                  userKey: admin-user
                  passwordKey: admin-password
                  ingress:
                    enabled: true
                  annotations: 
                  cert-manager.io/cluster-issuer: "letsencrypt-issuer"
                  kubernetes.io/ingress.class: nginx
                  nginx.ingress.kubernetes.io/service-upstream: "true"
                    # nginx-http-auth config:
                  nginx.ingress.kubernetes.io/auth-type: basic
                    # the name of the secret that contains the htpasswd hash (has to exist beforehand)
                  nginx.ingress.kubernetes.io/auth-secret: prometheus-htpasswd
                    # message to display on auth missing:
                  nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Grafana'
                  hosts:
                    - grafana.xxx
                  path: /
                  service:
                    name: prometheus-grafana
                  port: 3000
                  tls:
                    - secretName: grafana-xxx
                  hosts:
                    - grafana.xxx
                  persistence:
                    enabled: true
                  type: pvc
                  size: 10Gi
                  storageClassName: "myStorageClass"

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/kube-prometheus-stack --values values.yaml

**Comment by mschaefer-gresham** [comment]
I got this error because the pod couldn't write to the persistent storage location.

**Comment by martinbe1io** [comment]
same here

**Comment by luislhl** [comment]
> I got this error because the pod couldn't write to the persistent storage location.

I can confirm this. I was setting `grafana.containerSecurityContext.readOnlyRootFilesystem: true`, which was causing the problem.

Removing this fixed for me.

It seems the container only needs to write to `/tmp`, so a better solution could be to mount only `/tmp` as writable instead. But I haven't tested this yet.

**Comment by EHJ-52n** [comment]
I cannot confirm the existence of the value `grafana.containerSecurityContext.readOnlyRootFilesystem: true` in the `values.yaml` of the `kube-prometheus-stack` chart.

I am using

```
NAME            NAMESPACE           REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
prometheus      org-xyz-*****       70              2025-01-13 12:54:32.069248597 +0100 CET deployed        kube-prometheus-stack-67.8.0    v0.79.2 
```

**Comment by EHJ-52n** [comment]
I found the real cause of my problem by looking at the logs of the grafana container, only!

```
logger=grafana-apiserver t=2025-02-06T09:15:57.816347976Z level=info msg="StorageObjectCountTracker pruner is exiting"
Error: ✗ *api.HTTPServer run error: failed to open listener on address 0.0.0.0:443: listen tcp 0.0.0.0:443: bind: permission denied
```

This error was caused by the setting in our `values.yaml`, which were mislead by the comment above the `root_url` setting:

* **problematic** version:

  ```yaml
  [...]
  grafana
    grafana.ini:
      server:
        domain: monitor.example.com
        protocol: https
        http_port: "443"
        # The full public facing url you use in browser, used for redirects and emails
        root_url: "%(protocol)s://%(domain)s:%(http_port)s/prometheus/grafana"
        serve_from_sub_path: true
  [...]
  ```
 
* **working** version:

  ```yaml
  [...]
  grafana
    grafana.ini:
      server:
        domain: monitor.example.com
        # The full public facing url you use in browser, used for redirects and emails
        root_url: "https://%(domain)s/prometheus/grafana"
        serve_from_sub_path: true
  [...]
  ```

Hence, I think, the real error for this issue might not be the readiness probe, but something else preventing grafana from starting successfully.

In my case, I had some additional misleading loggings like the following:

```log
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/admin/provisioning/datasources/reload (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc1a68dd30>: Failed to establish a new connection: [Errno 111] Connection refused'))
GF_PATHS_CONFIG='/etc/grafana/grafana.ini' is not readable.
GF_PATHS_DATA='/var/lib/grafana/' is not writable.
GF_PATHS_HOME='/usr/share/grafana' is not readable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
logger=settings t=2025-02-06T09:15:53.721287796Z level=info msg="Starting Grafana" version=11.4.0 commit=b58701869e1a11b696010a6f28bd96b68a2cf0d0 branch=HEAD compiled=2025-02-06T09:15:53Z
logger=settings t=2025-02-06T09:15:53.721681856Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2025-02-06T09:15:53.721691774Z level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
```

I have the following findings regarding these logs
* The link to the grafana documentation is not resolving to something useful, because the page linked to does not deal with migration problems.
* The permission problems could not be verified because the files and folders were accessible to a container with the same `securityContext` and mounts.
